//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiecKin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.Seanse = new HashSet<Seans>();
        }
    
        public int id_filmu { get; set; }
        public string tytul { get; set; }
        public string rezyser { get; set; }
        public string gatunek { get; set; }
        public string kraj_produkcji { get; set; }
        public int ogr_wiekowe { get; set; }
        public System.DateTime grany_od { get; set; }
        public Nullable<System.DateTime> grany_do { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<Seans> Seanse { get; set; }
    }
}
