//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiecKin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kino
    {
        public Kino()
        {
            this.Sale = new HashSet<Sala>();
        }
    
        public int id_kina { get; set; }
        public string miejscowosc { get; set; }
        public string ulica { get; set; }
        public System.TimeSpan godz_otwarcia { get; set; }
        public System.TimeSpan godz_zamkniecia { get; set; }
    
        public virtual ICollection<Sala> Sale { get; set; }
    }
}
