//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiecKin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rzad
    {
        public Rzad()
        {
            this.Rezerwacje = new HashSet<Rezerwacja>();
        }
    
        public int id_rzedu { get; set; }
        public int id_sali { get; set; }
        public int id_kina { get; set; }
        public int liczba_miejsc { get; set; }
    
        public virtual ICollection<Rezerwacja> Rezerwacje { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
