//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiecKin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sala
    {
        public Sala()
        {
            this.Rzędy = new HashSet<Rzad>();
            this.Seanse = new HashSet<Seans>();
        }
    
        public int id_sali { get; set; }
        public string nazwa { get; set; }
        public int ilosc_rzedow { get; set; }
        public int id_kina { get; set; }
    
        public virtual Kino Kino { get; set; }
        public virtual ICollection<Rzad> Rzędy { get; set; }
        public virtual ICollection<Seans> Seanse { get; set; }
    }
}
