//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiecKin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seans
    {
        public Seans()
        {
            this.Rezerwacje = new HashSet<Rezerwacja>();
        }
    
        public int id_seansu { get; set; }
        public int id_filmu { get; set; }
        public int id_sali { get; set; }
        public int id_kina { get; set; }
        public System.DateTime data_rozpoczecia { get; set; }
        public System.DateTime czas_trwania { get; set; }
        public int id_formatu { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Format Format { get; set; }
        public virtual ICollection<Rezerwacja> Rezerwacje { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
