//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiecKin.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiecKinEntities : DbContext
    {
        public SiecKinEntities()
            : base("name=SiecKinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Film> Filmy { get; set; }
        public DbSet<Format> Formaty { get; set; }
        public DbSet<Kino> Kina { get; set; }
        public DbSet<Klient> Klienci { get; set; }
        public DbSet<Pracownik> Pracownicy { get; set; }
        public DbSet<Rezerwacja> Rezerwacje { get; set; }
        public DbSet<Rzad> Rzędy { get; set; }
        public DbSet<Sala> Sale { get; set; }
        public DbSet<Seans> Seanse { get; set; }
        public DbSet<TypBiletu> TypyBiletów { get; set; }
    }
}
