//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiecKin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypBiletu
    {
        public TypBiletu()
        {
            this.Rezerwacje = new HashSet<Rezerwacja>();
        }
    
        public int id_typu_biletu { get; set; }
        public decimal cena { get; set; }
        public string rodzaj { get; set; }
        public System.DateTime obowiazuje_od { get; set; }
        public Nullable<System.DateTime> obowiazuje_do { get; set; }
    
        public virtual ICollection<Rezerwacja> Rezerwacje { get; set; }
    }
}
